INSERT INTO public.firebase_user (id, unlocked_id, firebase_id, user_type, alias, roles, balance, customer_id, sub_checkout_session, paying) VALUES (37, null, 'doaihfnieanf', 'ultimate', null, 'a:2:{i:0;s:9:"ROLE_USER";i:1;s:13:"ROLE_ULTIMATE";}', 0, null, null, null);
INSERT INTO public.firebase_user (id, unlocked_id, firebase_id, user_type, alias, roles, balance, customer_id, sub_checkout_session, paying) VALUES (38, null, 'faoihfionezf', 'alpha', null, 'a:2:{i:0;s:9:"ROLE_USER";i:1;s:10:"ROLE_ALPHA";}', 0, null, null, null);
INSERT INTO public.firebase_user (id, unlocked_id, firebase_id, user_type, alias, roles, balance, customer_id, sub_checkout_session, paying) VALUES (39, null, 'fapojfjzpa', 'editor', null, 'a:2:{i:0;s:9:"ROLE_USER";i:1;s:11:"ROLE_EDITOR";}', 0, 'cus_klefnnzkef', 'cs_test_a1fSfwbyoIFNIE', true);
INSERT INTO public.firebase_user (id, unlocked_id, firebase_id, user_type, alias, roles, balance, customer_id, sub_checkout_session, paying) VALUES (9, null, 'faoifzinfe', 'ultimate', 'whrt51', 'a:2:{i:0;s:9:"ROLE_USER";i:1;s:10:"ROLE_ADMIN";}', 45.049996, 'cus_infzof', 'cs_test_a1CLEaWa1', true);

INSERT INTO public.website (id, name, aliases, locale, account_required, url, instagram, image_url, status, last_tested_at, cloud_api_url, cloud_api_identifier, estimated_captcha_cost, estimated_proxy_cost, fields, working) VALUES (6, 'Azerpas', null, 'fr-FR', false, 'http://test.azerpas.com/createEntry', null, 'https://cv.azerpas.com/assets/img/pic4.jpeg', 'not tested', '2020-07-11 22:00:00', null, null, 0, 0.000002, 'a:5:{i:0;s:5:"fname";i:1;s:5:"lname";i:2;s:5:"email";i:3;s:5:"phone";i:4;s:4:"size";}', null);

INSERT INTO public.product (id, name, brand, release_at, created_at, updated_at, pid, price, image_url, colorway, public, soleretriever_id) VALUES (1, 'Air Jordan 1 - Paname', 'Nike', '2020-10-11 10:02:48', '2020-10-11 10:02:48', '2020-10-11 10:02:48', '999999-999', 160, 'https://content.nike.com/content/dam/one-nike/globalAssets/social_media_images/nike_swoosh_logo_black.png', 'Royal Blue/Grey', true, null);
INSERT INTO public.product (id, name, brand, release_at, created_at, updated_at, pid, price, image_url, colorway, public, soleretriever_id) VALUES (2, 'Dunk SB - Pigeon', 'Nike', '2020-10-11 10:02:48', '2020-10-11 10:02:48', '2020-12-06 10:02:48', '999999-999', 100, 'https://content.nike.com/content/dam/one-nike/globalAssets/social_media_images/nike_swoosh_logo_black.png', 'Dark Red/White', false, '-100');

INSERT INTO public.raffle (id, website_id, product_id, created_at, updated_at, start_at, end_at, raffle_type, url, soleretriever_id) VALUES (2, 6, 1, null, null, null, null, 'ONLINE', 'http://test.azerpas.com/createEntry', null);
